# Users
FIRST_NAME_LENGTH = 64
LAST_NAME_LENGTH = 64

EMAIL_LENGTH = 256
DESCRIPTION_LENGTH = 2048

PLATFORM_NAME_LENGTH = 64  # depracted for PlatformEnum
LOCATION_NAME_LENGTH = 256
CERTIFICATE_LENGTH = 128
